# 💖 💔 
CUSTOM_PROMPT_SYMBOL=''
CUSTOM_TIME='%H:%M'
if is_windows; then
  ENABLE_PROMPT_GIT=0
  ENABLE_PROMPT_LAZE_GIT=1
  ENABLE_PROMPT_TIME=0
  ENABLE_PROMPT_USED_TIME=0
  ENABLE_USED_TIME_DISPLAY_DETAIL=0
else
  ENABLE_PROMPT_GIT=0
  ENABLE_PROMPT_LAZE_GIT=1
  ENABLE_PROMPT_TIME=1
  ENABLE_PROMPT_USED_TIME=1
  ENABLE_USED_TIME_DISPLAY_DETAIL=1
fi

ENABLE_CUSTOM_COMPLETE=1
export CURRENT_PID=$$

typeset -g LAST_COMMAND
typeset -g LAST_CMD_EXIT_STATUS
LAST_CMD_EXIT_STATUS=0

