# File: config.yaml

# Configure global settings
CompileFlags:
  Add: ["-Wall", "-Wextra"]


Style: File

Completion:
  AllScopes: Yes

Index:
  Background: Build

JavaScript:
Include: ["*.js", "*.jsx"]

