#!/usr/bin/env zsh
# Plugin manager
export ZPLUG_BIN=~/bin
export ZPLUG_THREADS=32
# If zplug doesn't exist, install it
ZPLUG_INIT=~/.zplug/init.zsh
[[ -f "$ZPLUG_INIT" ]] || curl -sL https://raw.githubusercontent.com/zplug/installer/master/installer.zsh |zsh
source "$ZPLUG_INIT"

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Git alias. See: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git
zplug "plugins/git", from:oh-my-zsh
# Git completions. On OS X with Homebrew, you need to install git with brew install git --without-completions. Otherwise, git's _git will take precedence, and you won't see the completions for git-extras commands.
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/extract", from:oh-my-zsh
zplug "plugins/zsh-history", from:oh-my-zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-word forward-char)
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)

################################################################################
# Themes
################################################################################
zplug "wfxr/spaceship-zsh-theme", use:spaceship.zsh, as:theme

zplug 'so-fancy/diff-so-fancy', \
    as:command, use:diff-so-fancy, \
    hook-build:'git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"'

#zplug "wfxr/formarks"
zplug 'wfxr/forgit', defer:1
FORGIT_FZF_DEFAULT_OPTS="
--height '80%'
"
zplug 'wfxr/pbcopy', as:command, use:'(*).sh', rename-to:'$1'

# jq is a lightweight and flexible command-line JSON processor.
(( $+commands[jq] )) || zplug "stedolan/jq", as:command, from:gh-r, rename-to:jq


# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    read -q && echo && zplug install
fi

zplug load
