#!/usr/bin/env zsh
alias python="/usr/local/bin/python2"
alias pip3="/usr/bin/pip3"
alias vim=nvim
alias vi=nvim
alias clang-format="/usr/local/Cellar/clang-format/12.0.1/share/clang/clang-format"
alias bat='bat --color=always --theme=TwoDark'
alias cat=/bin/cat
alias fdf='fd --type f --no-ignore-vcs --hidden --follow --exclude .o --exclude .git'
alias fdd='fd --type d --no-ignore-vcs --hidden --follow --exclude .o --exclude .git'
alias fdall='fd -I -a --hidden --follow --exclude .o --exclude .git'
alias date='/usr/local/opt/coreutils/libexec/gnubin/date'
alias rgg='rg --column --line-number --no-heading --color=always --with-filename --'
