#!/usr/bin/env zsh
#=============================================================================
#       Author: Wenxuan Zhang
#        Email: wenxuangm@gmail.com
#     HomePage: wenxuan.info
#=============================================================================

# Put this line on top to make keybinds work
bindkey -e

source ~/.myzsh/.fzf.zsh       2>/dev/null
source ~/.myzsh/.zsh_fzf_extra 2>/dev/null
source ~/.myzsh/.zsh_local     2>/dev/null
source ~/.myzsh/.zsh_secret    2>/dev/null

source ~/.myzsh/.zsh_plug
source ~/.myzsh/.zsh_keybinds
source ~/.myzsh/.zsh_theme
source ~/.myzsh/.zsh_aliases
source ~/.myzsh/.zsh_custom
source ~/.myzsh/.incr-0.2.zsh
#source ~/.zsh_docker

source ~/.zsh_theme 2>/dev/null
(( $+commands[thefuck] )) && source <(thefuck --alias 2>/dev/null)
(( $+commands[kubectl] )) && source <(kubectl completion zsh)
(( $+commands[pyenv]   )) && source <(pyenv init -)
#(( $+commands[fasd] ))    && source <(fasd --init auto)
#(( $+commands[pip] ))     && source <(pip completion --zsh)  # Too slow!

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#source ~/.sdkman/bin/sdkman-init.sh 2>/dev/null
#
#export CHROMIUM_BUILDTOOLS_PATH=/Users/zhangtongxiao/Desktop/yfd_work/sdk-demo-app-ios/tutor-engine-ios/live_engine/tutor-webrtc/src/buildtools/
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home
export ANDROID_HOME=/Users/zhangtongxiao/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=true
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
alias python="/usr/bin/python3"
export DEPOT_TOOLS_UPDATE=0

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#bindkey '^R' history-incremental-search-back

# Èò≤Ê≠¢ÈáçÂ§çÁöÑhistory
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP
setopt inc_append_history
setopt share_history

#source /codes/hobot/ph/arcanist/resources/shell/bash-completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
