# Put this line on top to make keybinds work
bindkey -e
source ~/.myzsh/zsh_aliases

. ~/bin/tool_function.sh
[ -e ~/.fzf.zsh ] && source ~/.fzf.zsh

SourceSh ~/.myzsh/zsh_plug
SourceSh ~/.myzsh/fzf.zsh
SourceSh ~/.myzsh/zsh_fzf_extra
SourceSh ~/.myzsh/zsh_theme
SourceSh ~/.myzsh/common.zsh
SourceSh ~/.myzsh/load_nvm.sh
SourceSh ~/.myzsh/zsh_path_config

